apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app  # Replace with your desired deployment name
spec:
  replicas: 2  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: xalien073/tmr_api:8914d8a33479138b1e3e938d6f3304aba9f9ba3c
          ports:
            - containerPort: 8000
      restartPolicy: Always  # Restart containers on failure
      # Define resource requests and limits for your application (optional)
      # resources:
      #   requests:
      #     memory: "100Mi"
      #     cpu: "100m"
      #   limits:
      #     memory: "200Mi"
      #     cpu: "200m"
