apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-cm # Replace with your desired config map name
data:
  MONGO_URI: "will replace"
  DATABASE_NAME: cuisine_reviews
  # Add other environment variables you need here
