replicaCount: 2

image:
  repository: xalien073/tmr_api
  tag: e64f562e100748f1ed68f2ffbe5645cd9d087768
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007

mongodb:
  uri: ""
  dbName: cuisine_reviews

resources: {}
