replicaCount: 2

image:
  repository: xalien073/tmr_api
  tag: 6c2268a75e23b163e99eae0ebf30fa9e61eeb953
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007

mongodb:
  uri: "will replace"
  dbName: cuisine_reviews

resources: {}
